th train.lua -input_h5 /data/coco/small_coco.h5 \
             -input_json /data/coco/small_coco_vocab.json \
             -gpu 1 \
             -batch_size 64 \
             -seq_length 45 \
             -model_type "lstm" \
             -wordvec_size 512 \
             -rnn_size 2048 \
             -num_layers 2 \
             -learning_rate 0.0005 \
             -checkpoint_every 250 \
             -lr_decay_every 5 \
             -max_epochs 500 
